'use strict';

/*
 * Jiangshan / Cross-era Generals — character expansion data
 *
 * This file is intentionally a classic script as well as a CommonJS module:
 * - browser builds read globalThis.CHARACTER_EXPANSION;
 * - local validation and Node consumers can require() the same object.
 *
 * The seven scores are fixed entertainment settings.  They are not historical
 * rankings, measurements, or claims about any person's real ability.
 */
const CHARACTER_EXPANSION = {
  factions: [
    {
      id: 'liubei',
      name: '刘备',
      era: '东汉末',
      style: '仁德聚众',
      role: '君主',
      description: '长于凝聚人才与安抚军心，疆域初定时恢复与守成更稳。',
      color: '#b56b5e',
      portrait: 'assets/portraits/liubei.webp',
      stats: {
        strength: 70, intelligence: 84, strategy: 82, charisma: 96,
        command: 86, development: 88, defense: 78,
      },
      initialRegion: null,
    },
    {
      id: 'zhangfei',
      name: '张飞',
      era: '东汉末',
      style: '据桥震军',
      role: '猛将',
      description: '正面冲击和据险拒守很强，适合在狭窄战线承担重压。',
      color: '#9c654c',
      portrait: 'assets/portraits/zhangfei.webp',
      stats: {
        strength: 97, intelligence: 55, strategy: 58, charisma: 70,
        command: 82, development: 55, defense: 84,
      },
      initialRegion: null,
    },
    {
      id: 'zhaoyun',
      name: '赵云',
      era: '东汉末至蜀汉',
      style: '救援持重',
      role: '统帅',
      description: '攻守转换与救援能力均衡，适合在多处相邻地盘维持战线。',
      color: '#66869a',
      portrait: 'assets/portraits/zhaoyun.webp',
      stats: {
        strength: 91, intelligence: 78, strategy: 82, charisma: 80,
        command: 90, development: 65, defense: 88,
      },
      initialRegion: null,
    },
    {
      id: 'zhouyu',
      name: '周瑜',
      era: '东汉末',
      style: '水军奇谋',
      role: '统帅',
      description: '善于统筹水陆战局并抓住战机，计谋和调度在交锋中更突出。',
      color: '#6b8890',
      portrait: 'assets/portraits/zhouyu.webp',
      stats: {
        strength: 74, intelligence: 92, strategy: 96, charisma: 88,
        command: 93, development: 78, defense: 78,
      },
      initialRegion: null,
    },
    {
      id: 'simayi',
      name: '司马懿',
      era: '东汉末至三国',
      style: '持重后发',
      role: '谋臣',
      description: '擅长忍耐、守势和长期筹划，战线拖长后更能发挥后手优势。',
      color: '#777d91',
      portrait: 'assets/portraits/simayi.webp',
      stats: {
        strength: 70, intelligence: 96, strategy: 95, charisma: 72,
        command: 86, development: 83, defense: 90,
      },
      initialRegion: null,
    },
    {
      id: 'sunquan',
      name: '孙权',
      era: '东汉末至三国吴',
      style: '据江纳贤',
      role: '君主',
      description: '长于据守江东、任用将才和经营资源，适合稳步扩大腹地。',
      color: '#5f8a7a',
      portrait: 'assets/portraits/sunquan.webp',
      stats: {
        strength: 68, intelligence: 84, strategy: 86, charisma: 90,
        command: 82, development: 92, defense: 88,
      },
      initialRegion: null,
    },
    {
      id: 'yuefei',
      name: '岳飞',
      era: '南宋',
      style: '精骑守边',
      role: '统帅',
      description: '重视军纪与战线推进，能把高强度攻守转化为稳定的阵地。本局未设置与其他在册人物的既定历史关系。',
      color: '#a07755',
      portrait: 'assets/portraits/yuefei.webp',
      stats: {
        strength: 95, intelligence: 86, strategy: 90, charisma: 89,
        command: 96, development: 70, defense: 91,
      },
      initialRegion: null,
    },
    {
      id: 'qijiguang',
      name: '戚继光',
      era: '明代',
      style: '练兵制胜',
      role: '统帅',
      description: '擅长训练、编制与因地用兵，准备充分时部队的持续作战更可靠。本局未设置与其他在册人物的既定历史关系。',
      color: '#8c6b58',
      portrait: 'assets/portraits/qijiguang.webp',
      stats: {
        strength: 88, intelligence: 84, strategy: 90, charisma: 82,
        command: 94, development: 76, defense: 86,
      },
      initialRegion: null,
    },
    {
      id: 'xiangyu',
      name: '项羽',
      era: '秦末楚汉之际',
      style: '破釜沉舟',
      role: '君主',
      description: '爆发力与决战能力极高，持续治理和后勤经营需要更谨慎。',
      color: '#746f83',
      portrait: 'assets/portraits/xiangyu.webp',
      stats: {
        strength: 99, intelligence: 62, strategy: 72, charisma: 84,
        command: 95, development: 54, defense: 68,
      },
      initialRegion: null,
    },
    {
      id: 'genghiskhan',
      name: '成吉思汗',
      era: '蒙古帝国早期',
      style: '草原驰突',
      role: '君主',
      description: '长于整合部众、远程机动和连续推进，跨区域作战的节奏很快。本局未设置与其他在册人物的既定历史关系。',
      color: '#8d7550',
      portrait: 'assets/portraits/genghiskhan.webp',
      stats: {
        strength: 92, intelligence: 88, strategy: 96, charisma: 95,
        command: 100, development: 82, defense: 77,
      },
      initialRegion: null,
    },
    {
      id: 'saladin',
      name: '萨拉丁',
      era: '阿尤布王朝',
      style: '宽治远征',
      role: '君主',
      description: '兼顾远征、整合和治理，面对长期对抗时士气与补给恢复较平衡。',
      color: '#a38158',
      portrait: 'assets/portraits/saladin.webp',
      stats: {
        strength: 82, intelligence: 91, strategy: 94, charisma: 93,
        command: 92, development: 86, defense: 85,
      },
      initialRegion: null,
    },
    {
      id: 'richard',
      name: '理查一世',
      era: '英格兰金雀花王朝',
      style: '狮心冲阵',
      role: '猛将',
      description: '决战和突击能力突出，远征型打法依赖稳定的粮草与后方。',
      color: '#78909a',
      portrait: 'assets/portraits/richard.webp',
      stats: {
        strength: 96, intelligence: 72, strategy: 78, charisma: 84,
        command: 90, development: 64, defense: 80,
      },
      initialRegion: null,
    },
  ],
  relationships: [
    {
      id: 'guanyu-liubei-allegiance',
      from: 'guanyu',
      to: 'liubei',
      type: 'allegiance',
      name: '旧主',
      description: '关羽与刘备早年结为兄弟并长期共同进退；本局以旧主关系表现，不等同于无条件归顺。',
    },
    {
      id: 'zhangfei-liubei-allegiance',
      from: 'zhangfei',
      to: 'liubei',
      type: 'allegiance',
      name: '旧主',
      description: '张飞长期追随刘备并担任蜀汉将领；本局以旧主关系表现，归顺仍需局势条件。',
    },
    {
      id: 'zhaoyun-liubei-allegiance',
      from: 'zhaoyun',
      to: 'liubei',
      type: 'allegiance',
      name: '旧主',
      description: '赵云后来追随刘备并成为蜀汉将领；本局以旧主关系表现，不改变个人固定属性。',
    },
    {
      id: 'zhugeliang-liubei-allegiance',
      from: 'zhugeliang',
      to: 'liubei',
      type: 'allegiance',
      name: '旧主',
      description: '诸葛亮受刘备三顾并辅佐蜀汉建立；本局允许以旧主关系呈现人才归属，仍受游戏门槛限制。',
    },
    {
      id: 'zhouyu-sunquan-allegiance',
      from: 'zhouyu',
      to: 'sunquan',
      type: 'allegiance',
      name: '旧主',
      description: '周瑜为孙吴核心将领并辅佐孙权；本局以旧主关系表现，不代表跨局或无条件服从。',
    },
    {
      id: 'sunquan-liubei-alliance',
      from: 'sunquan',
      to: 'liubei',
      type: 'alliance',
      name: '同盟',
      description: '孙权与刘备在赤壁前后形成共同抗曹的同盟背景；本局只降低相互敌对倾向，不强制结盟。',
    },
    {
      id: 'simayi-caocao-alliance',
      from: 'simayi',
      to: 'caocao',
      type: 'alliance',
      name: '同阵营',
      description: '司马懿曾在曹魏政治与军事体系中任职；本局只作为同阵营标签，不开放无限或自动归顺。',
    },
    {
      id: 'hanxin-xiangyu-rivalry',
      from: 'hanxin',
      to: 'xiangyu',
      type: 'rivalry',
      name: '楚汉对手',
      description: '韩信与项羽分属楚汉争霸两方；本局作为跨时代对手标签，具体战果仍由状态与随机数决定。',
    },
    {
      id: 'saladin-richard-rivalry',
      from: 'saladin',
      to: 'richard',
      type: 'rivalry',
      name: '十字军对手',
      description: '萨拉丁与理查一世在第三次十字军东征中处于交战两方；本局表现为宿敌倾向，不指定胜者。',
    },
  ],
};

if (typeof globalThis !== 'undefined') globalThis.CHARACTER_EXPANSION = CHARACTER_EXPANSION;
if (typeof module !== 'undefined' && module.exports) module.exports = CHARACTER_EXPANSION;
