#!/usr/bin/env python3
"""Validate the offline campaign catalogue's geometry and graph contracts.

This validator intentionally reads the classic JavaScript payload directly; it
does not use a browser, a map library, or a runtime network request.  It
checks the same invariants the static UI depends on: continuous region IDs,
reciprocal connected adjacency, one non-empty border per edge, playable
coverage, and complete vector land backgrounds.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
from collections import deque
from pathlib import Path

from shapely.geometry import Point, Polygon
from shapely.ops import unary_union

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "map-catalog.js"
EVIDENCE = ROOT / "work" / "campaign-map"
NUMBER = re.compile(r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?|[a-zA-Z]")


def load_catalog() -> list[dict]:
    source = CATALOG.read_text(encoding="utf-8")
    match = re.search(r"globalThis\.MAP_CATALOG\s*=\s*(\[.*\])\s*;\s*\n?if", source, flags=re.S)
    if not match:
        raise RuntimeError("map-catalog.js does not contain a classic MAP_CATALOG assignment")
    value = json.loads(match.group(1))
    if not isinstance(value, list):
        raise RuntimeError("MAP_CATALOG is not an array")
    return value


def path_rings(path: str) -> list[list[tuple[float, float]]]:
    """Parse the M/L/Z polygon paths emitted by the offline build script."""
    if not isinstance(path, str) or not path.strip():
        return []
    tokens = NUMBER.findall(path)
    index = 0
    command = None
    current = (0.0, 0.0)
    start = None
    active: list[tuple[float, float]] = []
    rings: list[list[tuple[float, float]]] = []

    def is_command(token: str) -> bool:
        return len(token) == 1 and token.isalpha()

    def read(count: int):
        nonlocal index
        if index + count > len(tokens) or any(is_command(t) for t in tokens[index:index + count]):
            return None
        values = [float(t) for t in tokens[index:index + count]]
        index += count
        return values if all(math.isfinite(v) for v in values) else None

    def flush():
        nonlocal active
        if len(active) >= 3:
            ring = active[:]
            if math.dist(ring[0], ring[-1]) < 1e-6:
                ring.pop()
            if len(ring) >= 3:
                rings.append(ring)
        active = []

    while index < len(tokens):
        if is_command(tokens[index]):
            command = tokens[index]
            index += 1
            if command.upper() == "Z":
                if start is not None:
                    if active and math.dist(active[-1], start) > 1e-6:
                        active.append(start)
                    flush()
                    current = start
                start = None
                command = None
            continue
        if not command:
            index += 1
            continue
        kind = command.upper()
        relative = command.islower()
        if kind not in {"M", "L"}:
            # Background/annotation curves are only required to be present;
            # region and border paths generated by this tool use M/L/Z.
            break
        values = read(2)
        if values is None:
            command = None
            continue
        point = (values[0] + current[0], values[1] + current[1]) if relative else (values[0], values[1])
        if kind == "M":
            if active:
                flush()
            current = point
            start = point
            active = [point]
            command = "l" if relative else "L"
        else:
            current = point
            active.append(point)
    flush()
    return rings


def path_polygon(path: str):
    polygons = []
    for ring in path_rings(path):
        try:
            poly = Polygon(ring)
            if poly.is_valid and poly.area > 1e-6:
                polygons.append(poly)
        except Exception:
            continue
    return unary_union(polygons) if polygons else Polygon()


def check_map(data: dict) -> dict:
    errors: list[str] = []
    map_id = data.get("id", "?")
    regions = data.get("regions") or []
    n = len(regions)
    ids = [r.get("id") for r in regions]
    if ids != list(range(n)):
        errors.append(f"region IDs are not continuous 0..{n - 1}")
    if not (30 <= n <= 52):
        errors.append(f"region count {n} is outside 30..52")
    if not all(isinstance(data.get(k), (int, float)) and data[k] > 0 for k in ("width", "height")):
        errors.append("width/height is invalid")
    bounds = data.get("bounds") or []
    if len(bounds) != 4 or not (bounds[0] < bounds[2] and bounds[1] < bounds[3]):
        errors.append("bounds is invalid")

    geometries = []
    for region in regions:
        geometry = path_polygon(region.get("path", ""))
        geometries.append(geometry)
        if geometry.is_empty or not geometry.is_valid:
            errors.append(f"region {region.get('id')} has an empty/invalid SVG polygon")
        x, y = region.get("x"), region.get("y")
        if not (isinstance(x, (int, float)) and isinstance(y, (int, float)) and math.isfinite(x) and math.isfinite(y)):
            errors.append(f"region {region.get('id')} has no finite anchor")
        elif geometry and not geometry.is_empty and not geometry.covers(Point(x, y)):
            errors.append(f"region {region.get('id')} anchor is outside its polygon")
        if region.get("terrain") not in {"plain", "mountain", "river"}:
            errors.append(f"region {region.get('id')} has invalid terrain")
        fertility = region.get("fertility")
        if not isinstance(fertility, (int, float)) or not 0.8 <= fertility <= 1.3:
            errors.append(f"region {region.get('id')} has invalid fertility")

    edge_set: set[tuple[int, int]] = set()
    for index, region in enumerate(regions):
        neighbours = region.get("neighbors") or []
        for other in neighbours:
            if not isinstance(other, int) or other < 0 or other >= n or other == index:
                errors.append(f"region {index} has invalid neighbor {other}")
                continue
            edge_set.add(tuple(sorted((index, other))))
            if index not in (regions[other].get("neighbors") or []):
                errors.append(f"adjacency {index}-{other} is not reciprocal")

    adjacency: dict[int, set[int]] = {i: set() for i in range(n)}
    for a, b in edge_set:
        adjacency[a].add(b)
        adjacency[b].add(a)
    seen = set()
    if n:
        queue = deque([0]); seen.add(0)
        while queue:
            current = queue.popleft()
            for other in adjacency[current]:
                if other not in seen:
                    seen.add(other); queue.append(other)
    if len(seen) != n:
        errors.append(f"adjacency graph has {n - len(seen)} disconnected regions")

    borders = data.get("borders") or []
    border_pairs: set[tuple[int, int]] = set()
    for border in borders:
        a, b = border.get("a"), border.get("b")
        pair = tuple(sorted((a, b))) if isinstance(a, int) and isinstance(b, int) else None
        if pair is None or a == b or a < 0 or b < 0 or a >= n or b >= n:
            errors.append(f"invalid border endpoints {a}-{b}")
            continue
        if pair in border_pairs:
            errors.append(f"duplicate border {a}-{b}")
        border_pairs.add(pair)
        if pair not in edge_set:
            errors.append(f"border {a}-{b} has no matching neighbor edge")
        if not isinstance(border.get("path"), str) or len(NUMBER.findall(border.get("path", ""))) < 4:
            errors.append(f"border {a}-{b} has an empty SVG path")
    if border_pairs != edge_set:
        errors.append(f"border/adjacency mismatch: {len(border_pairs)} borders vs {len(edge_set)} edges")

    region_union = unary_union(geometries) if geometries else Polygon()
    playable = path_polygon(data.get("playablePath") or data.get("landPath", ""))
    background = path_polygon(data.get("backgroundPath") or data.get("landPath", ""))
    if playable.is_empty or background.is_empty:
        errors.append("playable/background path is empty")
    else:
        ratio = region_union.symmetric_difference(playable).area / max(playable.area, 1)
        if ratio > 0.006:
            errors.append(f"region coverage differs from playable land by {ratio:.4%}")
        if background.area + 1e-6 < playable.area * 0.98:
            errors.append("background land is smaller than playable land")
        context = path_polygon(data.get("contextPath", ""))
        if not context.is_empty and context.intersection(playable).area / max(playable.area, 1) > 0.006:
            errors.append("context land overlaps playable land")

    audit = data.get("fragmentAudit") or {}
    threshold = float(audit.get("significantArea", 0.12))
    unassigned = [fragment for fragment in audit.get("fragments", []) if fragment.get("assignedTo") is None and float(fragment.get("area", 0)) >= threshold]
    # The accepted central map predates this catalogue and intentionally keeps
    # one remote northeast background fragment outside the 52 playable cells.
    # New campaign maps must satisfy the stricter coverage contract.
    if map_id == "central":
        unassigned = []
    if unassigned:
        errors.append(f"{len(unassigned)} significant discarded land fragments remain unassigned")
    if not isinstance(data.get("backgroundPath"), str) or not data["backgroundPath"]:
        errors.append("campaign map has no complete backgroundPath")
    background_image = data.get("backgroundImage")
    if not isinstance(background_image, str) or not background_image:
        errors.append("map has no extent-aligned relief image")
    elif "terrain.webp" in background_image or not (ROOT / background_image).exists():
        errors.append(f"relief image is missing or reuses central terrain.webp: {background_image}")
    background_frame = data.get("backgroundBounds")
    image_frame = data.get("backgroundImageBounds")
    for key, frame in (("backgroundBounds", background_frame), ("backgroundImageBounds", image_frame)):
        if not isinstance(frame, dict) or not all(isinstance(frame.get(item), (int, float)) and math.isfinite(frame[item]) for item in ("x", "y", "width", "height")) or frame.get("width", 0) <= 0 or frame.get("height", 0) <= 0:
            errors.append(f"{key} is missing or invalid")
    if isinstance(background_frame, dict) and all(isinstance(background_frame.get(item), (int, float)) for item in ("width", "height")):
        if background_frame["width"] < data["width"] * 3 or background_frame["height"] < data["height"] * 3:
            errors.append("background extent is too small for minimum zoom")
    if isinstance(background_frame, dict) and isinstance(image_frame, dict):
        if any(abs(background_frame[item] - image_frame[item]) > 0.01 for item in ("x", "y", "width", "height")):
            errors.append("background image frame is not aligned with background extent")
    if map_id != "central" and not playable.is_empty:
        minx, miny, maxx, maxy = playable.bounds
        if abs(minx) < 0.01 and abs(miny) < 0.01 and abs(maxx - data["width"]) < 0.01 and abs(maxy - data["height"]) < 0.01:
            errors.append("campaign playable land is still a synthetic hard rectangle")
    if map_id != "central" and len(data.get("barrierPaths") or []) < 2:
        errors.append("campaign map has too few named natural barriers")
    if map_id != "central" and len(data.get("expeditionSites") or []) != 3:
        errors.append("campaign map does not define three expedition sites")
    for site in data.get("expeditionSites") or []:
        if not (isinstance(site.get("distance"), int) and 1 <= site["distance"] <= 12):
            errors.append(f"expedition {site.get('id')} has invalid distance")
        if not (isinstance(site.get("difficulty"), int) and 1 <= site["difficulty"] <= 100):
            errors.append(f"expedition {site.get('id')} has invalid difficulty")
        if not (isinstance(site.get("cooldownMonths"), int) and 1 <= site["cooldownMonths"] <= 60):
            errors.append(f"expedition {site.get('id')} has invalid cooldown")
        if not isinstance(site.get("rewards"), dict):
            errors.append(f"expedition {site.get('id')} has no rewards object")

    if errors:
        raise RuntimeError(map_id + ": " + "; ".join(errors))
    return {
        "id": map_id,
        "regions": n,
        "edges": len(edge_set),
        "borderPaths": len(border_pairs),
        "connected": True,
        "coverageDifference": round(region_union.symmetric_difference(playable).area / max(playable.area, 1), 8),
        "playableAreaPx": round(playable.area, 2),
        "backgroundAreaPx": round(background.area, 2),
        "playableBoundsPx": [round(value, 2) for value in playable.bounds] if not playable.is_empty else [],
        "backgroundBounds": data.get("backgroundBounds"),
        "backgroundImage": data.get("backgroundImage"),
        "rivers": len(data.get("rivers") or []),
        "barriers": len(data.get("barrierPaths") or []),
        "expeditionSites": len(data.get("expeditionSites") or []),
    }


def main() -> None:
    catalog = load_catalog()
    expected = {"central", "north", "south", "mediterranean"}
    actual = {item.get("id") for item in catalog}
    if actual != expected:
        raise RuntimeError(f"catalog IDs {sorted(actual)} do not match {sorted(expected)}")
    summaries = [check_map(item) for item in catalog]
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    evidence = {
        "catalog": str(CATALOG),
        "catalogSha256": hashlib.sha256(CATALOG.read_bytes()).hexdigest(),
        "maps": summaries,
        "status": "PASS",
    }
    (EVIDENCE / "validation.json").write_text(json.dumps(evidence, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(evidence, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
